# FIXME: https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html

- name: Main
  hosts: all
  remote_user: admin
  become: yes
  vars: # FIXME: vars list is deprecated
   - project: server-tutorial

  tasks:
    - name: Ping hosts
      ansible.builtin.ping:

    - name: Copy backend to host
      ansible.builtin.copy:
        src: ../../code/target/server-tutorial.war
        dest: /tmp/target/
        mode: "0755"

    - name: Install GPG
      ansible.builtin.apt:
       name: gnupg2
       state: latest
       update_cache: yes # because https://github.com/geerlingguy/ansible-role-kibana/issues/65

    - name: Add docker GPG apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add docker repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/debian bookworm stable
        state: present

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Ensure container is absent
      community.docker.docker_container:
        name: "{{project}}"
        state: absent

    - name: Start container
      community.docker.docker_container:
        name: "{{project}}"
        image: "tomcat:11.0.1-jdk21-temurin-noble"
        state: started
        restart_policy: always
        ports: "80:8080"
        volumes:
          - "/tmp/target:/usr/local/tomcat/webapps/"
